<?php

return [
    [
        'reference' => 'APT000001',
        'address' => 'Via Roma 1',
        'cap' => '00100',
        'city' => 'Roma',
        'state' => 'Lazio',
        'square_meters' => 80,
        'rooms' => 3,
        'bathrooms' => 2,
        'type' => 'Appartamento',
        'description' => 'Luminoso appartamento in centro città, vicino a tutti i servizi.',
        'price' => 250000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'A+',
    ],
    [
        'reference' => 'APT000651',
        'address' => 'Via Roma 1',
        'cap' => '00100',
        'city' => 'Roma',
        'state' => 'Lazio',
        'square_meters' => 80,
        'rooms' => 3,
        'bathrooms' => 2,
        'type' => 'Appartamento',
        'description' => 'Luminoso appartamento in centro città, vicino a tutti i servizi.',
        'price' => 250000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'A+',
    ],
    [
        'reference' => 'APT000002',
        'address' => 'Via Milano 10',
        'cap' => '20100',
        'city' => 'Milano',
        'state' => 'Lombardia',
        'square_meters' => 60,
        'rooms' => 2,
        'bathrooms' => 1,
        'type' => 'Appartamento',
        'description' => 'Appartamento moderno in zona tranquilla e ben collegata.',
        'price' => 200000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'B',
    ],
    [
        'reference' => 'APT000003',
        'address' => 'Corso Torino 5',
        'cap' => '10100',
        'city' => 'Torino',
        'state' => 'Piemonte',
        'square_meters' => 75,
        'rooms' => 3,
        'bathrooms' => 2,
        'type' => 'Appartamento',
        'description' => 'Appartamento in zona residenziale, ideale per famiglie.',
        'price' => 220000.00,
        'is_avaliable' => 0,
        'energy_rating' => 'A',
    ],
    [
        'reference' => 'APT000004',
        'address' => 'Via Napoli 8',
        'cap' => '80100',
        'city' => 'Napoli',
        'state' => 'Campania',
        'square_meters' => 90,
        'rooms' => 4,
        'bathrooms' => 2,
        'type' => 'Appartamento',
        'description' => 'Appartamento con vista mare, ristrutturato recentemente.',
        'price' => 280000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'A+',
    ],
    [
        'reference' => 'APT000005',
        'address' => 'Via Firenze 3',
        'cap' => '50100',
        'city' => 'Firenze',
        'state' => 'Toscana',
        'square_meters' => 85,
        'rooms' => 3,
        'bathrooms' => 1,
        'type' => 'Appartamento',
        'description' => 'Appartamento con terrazzo panoramico in zona collinare.',
        'price' => 260000.00,
        'is_avaliable' => 0,
        'energy_rating' => 'B+',
    ],
    [
        'reference' => 'APT000006',
        'address' => 'Via Palermo 22',
        'cap' => '90100',
        'city' => 'Palermo',
        'state' => 'Sicilia',
        'square_meters' => 70,
        'rooms' => 3,
        'bathrooms' => 1,
        'type' => 'Appartamento',
        'description' => 'Appartamento in centro storico, ottimo investimento.',
        'price' => 180000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'C',
    ],
    [
        'reference' => 'APT000007',
        'address' => 'Via Venezia 7',
        'cap' => '30100',
        'city' => 'Venezia',
        'state' => 'Veneto',
        'square_meters' => 60,
        'rooms' => 2,
        'bathrooms' => 1,
        'type' => 'Appartamento',
        'description' => 'Appartamento storico, ideale per affitti brevi.',
        'price' => 300000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'B',
    ],
    [
        'reference' => 'APT000008',
        'address' => 'Via Bologna 13',
        'cap' => '40100',
        'city' => 'Bologna',
        'state' => 'Emilia-Romagna',
        'square_meters' => 90,
        'rooms' => 4,
        'bathrooms' => 2,
        'type' => 'Appartamento',
        'description' => 'Appartamento di lusso con finiture di pregio.',
        'price' => 400000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'A+',
    ],
    [
        'reference' => 'APT000009',
        'address' => 'Via Bari 5',
        'cap' => '70100',
        'city' => 'Bari',
        'state' => 'Puglia',
        'square_meters' => 100,
        'rooms' => 5,
        'bathrooms' => 3,
        'type' => 'Appartamento',
        'description' => 'Appartamento signorile in zona centrale.',
        'price' => 320000.00,
        'is_avaliable' => 0,
        'energy_rating' => 'A',
    ],
    [
        'reference' => 'APT000010',
        'address' => 'Via Cagliari 9',
        'cap' => '09100',
        'city' => 'Cagliari',
        'state' => 'Sardegna',
        'square_meters' => 80,
        'rooms' => 3,
        'bathrooms' => 2,
        'type' => 'Appartamento',
        'description' => 'Appartamento con giardino privato e posto auto.',
        'price' => 270000.00,
        'is_avaliable' => 1,
        'energy_rating' => 'B+',
    ]
    ];
